// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhsnxqudszqytfilgivp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoc254cXVkc3pxeXRmaWxnaXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDU1NzAsImV4cCI6MjA2NDgyMTU3MH0.87ZVV_sAWfohpvH18C9NmpX9m3eQ17Z4-E_mFN2ZDWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);